# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-19 13:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rules', models.TextField(blank=True)),
                ('surname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=255, verbose_name='Отчество')),
                ('email', models.EmailField(max_length=254, verbose_name='email адрес')),
                ('post', models.CharField(max_length=255, verbose_name='Должность')),
                ('work_place', models.CharField(max_length=2000, verbose_name='Место работы')),
                ('file', models.FileField(upload_to='contact', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('message', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactAdminStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
            ],
        ),
        migrations.AddField(
            model_name='contactadmin',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contact.ContactAdminStatus', verbose_name='Статус обращениея'),
        ),
    ]
