# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-20 10:11
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactadmin',
            name='rules',
        ),
        migrations.AddField(
            model_name='contactadmin',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default=79000000000, max_length=128, verbose_name='номер телефона'),
            preserve_default=False,
        ),
    ]
