# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-21 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20180420_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactadmin',
            name='contact_choice',
            field=models.CharField(choices=[('A', 'Руководителю компании'), ('E', 'Эксперту')], default='А', max_length=1, verbose_name='Кому адресовано'),
        ),
        migrations.AlterField(
            model_name='contactadmin',
            name='post',
            field=models.CharField(choices=[('G', 'Государственный служащий')], default='G', max_length=1, verbose_name='Должность'),
        ),
    ]
