# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 08:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20180424_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactadmin',
            name='creation_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactadmin',
            name='update_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
