# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-27 04:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_auto_20180424_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactAdminResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email получателя')),
                ('message', models.TextField(blank=True, verbose_name='Текст сообщения')),
                ('attach', models.TextField(blank=True, verbose_name='Файл вложения')),
                ('status', models.BooleanField(editable=False, verbose_name='Отправлено')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name_plural': 'Ответы администратора',
                'verbose_name': 'Ответ администратора',
            },
        ),
        migrations.AlterModelOptions(
            name='contactadmin',
            options={'verbose_name': 'Обращение к администратору', 'verbose_name_plural': 'Обращения к администратору'},
        ),
        migrations.AlterModelOptions(
            name='contactadminstatus',
            options={'verbose_name': 'Статус ответа администратора', 'verbose_name_plural': 'Статусы ответа администратора'},
        ),
        migrations.AlterField(
            model_name='contactadmin',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contact.ContactAdminStatus', verbose_name='Статус обращения'),
        ),
        migrations.AddField(
            model_name='contactadmin',
            name='response',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='contact.ContactAdminResponse', verbose_name='Ответ'),
        ),
    ]
