# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-27 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_auto_20180427_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactadminresponse',
            name='attach',
            field=models.FileField(blank=True, null=True, upload_to='contact/%Y/', verbose_name='Файл вложения'),
        ),
    ]
