# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-07 10:49
from __future__ import unicode_literals

import contact.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_auto_20180427_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactadminresponse',
            name='type',
            field=models.CharField(choices=[('R', 'Ответ'), ('F', 'Перенаправление')], default='R', max_length=1, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='contactadmin',
            name='contact_choice',
            field=models.CharField(choices=[('A', 'Руководителю компании'), ('E', 'Администратору сайта')], default='А', max_length=1, verbose_name='Кому адресовано'),
        ),
        migrations.AlterField(
            model_name='contactadmin',
            name='creation_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата поступления'),
        ),
        migrations.AlterField(
            model_name='contactadmin',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='contact/%Y/', validators=[contact.validators.FileValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xlsx', 'xls', 'jpg', 'png', 'zip', 'rar'], max_size=20971520)], verbose_name='Файл вложения (не более 20 мб)'),
        ),
        migrations.AlterField(
            model_name='contactadmin',
            name='post',
            field=models.CharField(choices=[('R', 'Руководитель компании'), ('P', 'Представитель компании'), ('I', 'Индивидуальный предприниматель'), ('Z', 'Инженер компании'), ('G', 'Государственный служащий'), ('F', 'Гражданин РФ'), ('S', 'Студент'), ('E', 'Пенсионер'), ('O', 'Общественный деятель'), ('C', 'Представитель СРО'), ('D', 'Депутат'), ('C', 'Судья'), ('U', 'Представитель прокуратуры'), ('M', 'Представитель органов МВД / ФСБ'), ('N', 'Представитель налоговой службы'), ('A', 'Другое')], default='G', max_length=1, verbose_name='Должность / социальное положение'),
        ),
        migrations.AlterField(
            model_name='contactadmin',
            name='response',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contact.ContactAdminResponse', verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='contactadmin',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contact.ContactAdminStatus', verbose_name='Статус обращения'),
        ),
        migrations.AlterField(
            model_name='contactadminresponse',
            name='creation_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата ответа'),
        ),
    ]
