# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-07 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0009_auto_20180507_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactadmin',
            name='response',
        ),
        migrations.AddField(
            model_name='contactadminresponse',
            name='response',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='contact.ContactAdmin', verbose_name='Ответ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactadmin',
            name='post',
            field=models.CharField(choices=[('R', 'Руководитель компании'), ('P', 'Представитель компании'), ('I', 'Индивидуальный предприниматель'), ('Z', 'Инженер компании'), ('G', 'Государственный служащий'), ('F', 'Гражданин РФ'), ('S', 'Студент'), ('E', 'Пенсионер'), ('O', 'Общественный деятель'), ('C', 'Представитель СРО'), ('D', 'Депутат'), ('C', 'Судья'), ('U', 'Представитель прокуратуры'), ('M', 'Представитель органов МВД / ФСБ'), ('N', 'Представитель налоговой службы'), ('A', 'Другое')], default='P', max_length=1, verbose_name='Должность / социальное положение'),
        ),
    ]
