# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-07 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0010_auto_20180507_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactadminresponse',
            name='response',
        ),
        migrations.AddField(
            model_name='contactadmin',
            name='response',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='response', to='contact.ContactAdminResponse', verbose_name='Обращение'),
        ),
    ]
