# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-07 15:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0011_auto_20180507_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactadminresponse',
            name='status',
        ),
    ]
