# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-17 08:49
from __future__ import unicode_literals

import contact.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0012_remove_contactadminresponse_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactExpert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, verbose_name='номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='email адрес')),
                ('post', models.CharField(choices=[('R', 'Руководитель компании'), ('P', 'Представитель компании'), ('I', 'Индивидуальный предприниматель'), ('Z', 'Инженер компании'), ('G', 'Государственный служащий'), ('F', 'Гражданин РФ'), ('S', 'Студент'), ('E', 'Пенсионер'), ('O', 'Общественный деятель'), ('C', 'Представитель СРО'), ('D', 'Депутат'), ('C', 'Судья'), ('U', 'Представитель прокуратуры'), ('M', 'Представитель органов МВД / ФСБ'), ('N', 'Представитель налоговой службы'), ('A', 'Другое')], default='P', max_length=1, verbose_name='Должность / социальное положение')),
                ('work_place', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Место работы')),
                ('file', models.FileField(blank=True, null=True, upload_to='contact/%Y/', validators=[contact.validators.FileValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xlsx', 'xls', 'jpg', 'png', 'zip', 'rar'], max_size=20971520)], verbose_name='Файл вложения (не более 20 мб)')),
                ('message', models.TextField(blank=True, verbose_name='Текст сообщения')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата поступления')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('response', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contact.ContactAdminResponse', verbose_name='Ответ')),
            ],
            options={
                'verbose_name_plural': 'Обращения к эксперту',
                'verbose_name': 'Обращение к эксперту',
            },
        ),
        migrations.CreateModel(
            name='ContactExpertStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name_plural': 'Статусы ответа эксперта',
                'verbose_name': 'Статус ответа эксперта',
            },
        ),
        migrations.AlterField(
            model_name='contactadmin',
            name='response',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contact.ContactAdminResponse', verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='contactadmin',
            name='status',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='contact.ContactAdminStatus', verbose_name='Статус обращения'),
        ),
        migrations.AddField(
            model_name='contactexpert',
            name='status',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='contact.ContactExpertStatus', verbose_name='Статус обращения'),
        ),
    ]
