# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-17 09:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0013_auto_20180517_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactExpertResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email получателя')),
                ('message', models.TextField(blank=True, verbose_name='Текст сообщения')),
                ('attach', models.FileField(blank=True, null=True, upload_to='contact/%Y/', verbose_name='Файл вложения')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата ответа')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('type', models.CharField(choices=[('R', 'Ответ'), ('F', 'Перенаправление')], default='R', max_length=1, verbose_name='Тип')),
            ],
            options={
                'verbose_name_plural': 'Ответы эксперта',
                'verbose_name': 'Ответ эксперта',
            },
        ),
        migrations.AlterField(
            model_name='contactexpert',
            name='response',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contact.ContactExpertResponse', verbose_name='Ответ'),
        ),
    ]
