# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-20 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0014_auto_20180517_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ExpertResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=1000)),
                ('text', models.TextField()),
                ('file', models.FileField(upload_to='')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.Expert')),
            ],
            options={
                'verbose_name': 'Ответ эксперта',
                'verbose_name_plural': 'Ответы эксперта',
            },
        ),
        migrations.AlterModelOptions(
            name='contactexpertresponse',
            options={'verbose_name': 'Ответ эксперта админа', 'verbose_name_plural': 'Ответы эксперта админа'},
        ),
        migrations.AddField(
            model_name='contactexpert',
            name='subject',
            field=models.CharField(choices=[('R', 'Другое')], default='R', max_length=1, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='contactexpert',
            name='expert_responses',
            field=models.ManyToManyField(to='contact.ExpertResponse'),
        ),
    ]
