# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-20 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0015_auto_20180520_1158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expert',
            options={'verbose_name': 'Эксперт', 'verbose_name_plural': 'Эксперты'},
        ),
        migrations.RemoveField(
            model_name='contactexpert',
            name='expert_responses',
        ),
        migrations.AddField(
            model_name='expertresponse',
            name='contact_responses',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contact.ContactExpert'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expertresponse',
            name='response_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactexpert',
            name='subject',
            field=models.CharField(choices=[('R', 'Другое')], default='R', max_length=1, verbose_name='Тема обращения'),
        ),
    ]
