# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-20 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0016_auto_20180520_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactexpertresponse',
            name='type',
        ),
        migrations.RemoveField(
            model_name='expertresponse',
            name='contact_responses',
        ),
        migrations.AddField(
            model_name='expertresponse',
            name='contact_response',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='expertresponse', to='contact.ContactExpert', verbose_name='ответ экспертов'),
            preserve_default=False,
        ),
    ]
