# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-31 08:38
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0017_auto_20180520_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertresponse',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
