# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-31 10:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0018_expertresponse_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expertresponse',
            old_name='contact_response',
            new_name='contact_expert_question',
        ),
    ]
