# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-31 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0019_auto_20180531_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertresponse',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='expert_responses/%Y/', verbose_name='приложить файл'),
        ),
        migrations.AlterField(
            model_name='expertresponse',
            name='subject',
            field=models.CharField(max_length=1000, verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='expertresponse',
            name='text',
            field=models.TextField(verbose_name='Ответ'),
        ),
    ]
