# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-08 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0020_auto_20180531_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactexpert',
            name='subject',
        ),
        migrations.AlterField(
            model_name='expertresponse',
            name='response_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата ответа'),
        ),
    ]
